export const configurations = {
  cap1: {
    caption: "Capitulo 1",
    title: "La misión comienza",
    question: "¿Cómo comienza Bryan su viaje?",
    paragraph:
      "Bryan, en su hogar en el bosque intergaláctico, recibe un mensaje de emergencia. El Gran Árbol de la Vida, que mantiene la paz y el equilibrio en su galaxia, está muriendo. Bryan debe recolectar ingredientes mágicos que están desperdigados por diferentes planetas y entregarlos a tiempo.",
    button1Text:
      "Monta su motocicleta intergaláctica para llegar al primer planeta",
    button2Text: "Usa su avión para viajar más rápido.",
    buttonMainColor: "#034801",
    buttonSecondaryColor: "#EEF700",
    links: {
      button1Link: "librojuego.html?theme=cap2a",
      button2Link: "librojuego.html?theme=cap2b",
    },
    backgroundImage: "./multimedia/historia/capitulo1-bg.webp",
    vectorImage: "./multimedia/historia/capitulo1-vector.svg",
    showButton2: true,
    showQuestion: true,
  },
  cap2a: {
    caption: "Capitulo 2",
    title: "El Planeta de los Vientos Eternos",
    question: "¿Cómo enfrenta Bryan las tormentas?",
    paragraph:
      "Bryan llega a un planeta lleno de tormentas de viento. Necesita atravesar un campo de rocas flotantes para obtener el 'Polvo de Estrellas'.",
    button1Text: "Construye un refugio temporal",
    button2Text: "Se arriesga y avanza a toda velocidad",
    buttonMainColor: "#DD4F06",
    buttonSecondaryColor: "#FAE512",
    links: {
      button1Link: "librojuego.html?theme=cap2aa",
      button2Link: "librojuego.html?theme=cap2ab",
    },
    backgroundImage: "./multimedia/historia/capitulo2a-bg.webp",
    vectorImage: "./multimedia/historia/capitulo2a-vector.svg",
    showButton2: true,
    showQuestion: true,
  },
  cap2b: {
    caption: "Capitulo 2",
    title: "El Planeta de los Bosques Cantantes",
    question: "¿Cómo convence a los árboles para que le den el néctar?",
    paragraph:
      "Bryan aterriza en un bosque mágico donde los árboles cantan. Allí debe encontrar el Néctar de la Armonía.",
    button1Text: "Toca una melodía con su guitarra",
    button2Text: "Usa el lazo de vaquero para recoger el néctar directamente",
    buttonMainColor: "#361360",
    buttonSecondaryColor: "#EBCCF8",
    links: {
      button1Link: "librojuego.html?theme=cap2ba",
      button2Link: "librojuego.html?theme=cap2bb",
    },
    backgroundImage: "./multimedia/historia/capitulo2b-bg.webp",
    vectorImage: "./multimedia/historia/capitulo2b-vector.svg",
    showButton2: true,
    showQuestion: true,
  },
  cap2aa: {
    caption: "El final de la aventura",
    title: "El Aventurero Eterno",
    question: "",
    paragraph:
      "Bryan decide construir un refugio temporal en el planeta de los vientos. Durante su estadía, descubre recursos únicos y un antiguo mapa estelar oculto en una cueva cercana. Aunque no logra salvar el Gran Árbol de la Vida, su curiosidad lo guía hacia nuevos horizontes. Con el mapa en mano, Bryan abandona el bosque intergaláctico para explorar los rincones más desconocidos del universo, convirtiéndose en una leyenda de la exploración galáctica.",
    button1Text: "Ir al inicio",
    button2Text: "Registrar puntaje",
    buttonMainColor: "#0800E2",
    buttonSecondaryColor: "#D1CFFF",
    links: {
      button1Link: "index.html",
      button2Link: "registrar-puntaje.html",
    },
    backgroundImage: "./multimedia/historia/final2aa-bg.webp",
    vectorImage: "./multimedia/historia/final2aa-vector.svg",
    showButton2: true,
    showQuestion: false,
  },
  cap2ab: {
    caption: "El final de la aventura",
    title: "Bryan salva el bosque intergaláctico",
    question: "",
    paragraph:
      "Bryan logra recolectar el Polvo de Estrellas enfrentando las tormentas y, con valentía, se enfrenta al desafío del bosque cantante. Usando su guitarra, consigue el Néctar de la Armonía y revive al Gran Árbol de la Vida. Gracias a su éxito, el bosque florece nuevamente, Bryan es reconocido como un héroe intergaláctico y el bosque le regala miles de dólares.",
    button1Text: "Ir al inicio",
    button2Text: "Registrar puntaje",
    buttonMainColor: "#0D140B",
    buttonSecondaryColor: "#75B25C",
    links: {
      button1Link: "index.html",
      button2Link: "registrar-puntaje.html",
    },
    backgroundImage: "./multimedia/historia/final2ab-bg.webp",
    vectorImage: "./multimedia/historia/final2ab-vector.svg",
    showButton2: true,
    showQuestion: false,
  },
  cap2ba: {
    caption: "El final de la aventura",
    title: "El Creador de Galaxias",
    question: "",
    paragraph:
      "Bryan, con su guitarra en mano, decide tocar una melodía ancestral mientras camina por el bosque intergaláctico. La vibración de las cuerdas despierta una energía cósmica en el aire, abriendo un portal hacia un vasto universo lleno de nuevas estrellas y planetas.  La melodía, como una llave cósmica, le otorga a Bryan el poder de dar forma a nuevas galaxias. Mientras se convierte en un creador del universo, su música se difunde por todo el cosmos. Bryan, ahora conocido como el Creador de Galaxias, viaja entre estrellas, dejando su huella en cada rincón del espacio.",
    button1Text: "Ir al inicio",
    button2Text: "Registrar puntaje",
    buttonMainColor: "#310065",
    buttonSecondaryColor: "#D39AFF",
    links: {
      button1Link: "index.html",
      button2Link: "registrar-puntaje.html",
    },
    backgroundImage: "./multimedia/historia/final2ba-bg.webp",
    vectorImage: "./multimedia/historia/final2ba-vector.svg",
    showButton2: true,
    showQuestion: false,
  },
  cap2bb: {
    caption: "El final de la aventura",
    title: "El Chef del Bosque Estelar",
    question: "",
    paragraph:
      "Bryan, con su lazo de vaquero, se adentra en el bosque intergaláctico, donde las flores producen un néctar de sabores exquisitos. Usando su destreza, recoge el néctar directamente, creando una mezcla única que no solo tiene un sabor increíble, sino propiedades curativas. Con esta receta secreta, Bryan abre un restaurante flotante en el espacio, donde todos los seres del bosque y más allá vienen a probar sus platillos, convirtiéndolo en el chef más famoso del universo.",
    button1Text: "Ir al inicio",
    button2Text: "Registrar puntaje",
    buttonMainColor: "#DD4F06",
    buttonSecondaryColor: "#FAE512",
    links: {
      button1Link: "index.html",
      button2Link: "registrar-puntaje.html",
    },
    backgroundImage: "./multimedia/historia/final2bb-bg.webp",
    vectorImage: "./multimedia/historia/final2bb-vector.svg",
    showButton2: true,
    showQuestion: false,
  },
};
